---
- name: CNI | Ensure CNI directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 'u+rw,g+r,o+r'
  with_items:
    - "{{ cni_bin_dir }}"
    - "{{ cni_conf_dir }}"

- name: CNI | Download CNI plugins binaries
  ansible.builtin.unarchive:
    src: "{{ cni_plugins_release_url }}"
    dest: "{{ cni_bin_dir }}"
    remote_src: true
